# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

let
  bootFat32Uuid = "8D00-3C46";
  swapUuid = "957ad7d5-a678-41d2-9f05-296d244fa5fe";
  nvmeBtrfsUuid = "b88c4b4d-16c2-4ede-8927-66cd954d0799";
  hddBtrfsUuid = "30e4bc15-cf9d-4e23-8ef7-2db14db18bd1";
in {
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "usb_storage" "sd_mod" "rtsx_pci_sdmmc" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  # space_cache (?)
  # https://wiki.tnonline.net/w/Btrfs/Space_Cache

  fileSystems = {

    "/boot" = {
      device = "/dev/disk/by-uuid/${bootFat32Uuid}";
      fsType = "vfat";
    };

    "/" = {
      device = "/dev/disk/by-uuid/${nvmeBtrfsUuid}";
      fsType = "btrfs";
      options = [ "subvol=root" "compress=zstd" ];
    };

    "/nix" = {
      device = "/dev/disk/by-uuid/${nvmeBtrfsUuid}";
      fsType = "btrfs";
      options = [ "subvol=nix" "compress=zstd" "noatime" ];
    };

    "/home" = {
      device = "/dev/disk/by-uuid/${nvmeBtrfsUuid}";
      fsType = "btrfs";
      options = [ "subvol=home" "compress=zstd" ];
    };

    "/home/marcosrdac/tmp" = {
      device = "/dev/disk/by-uuid/${hddBtrfsUuid}";
      fsType = "btrfs";
      options = [ "subvol=@marcosrdac/@tmp" "compress=zstd" ];
    };

  };

  swapDevices = [
    { device = "/dev/disk/by-uuid/${swapUuid}"; }
  ];


  #fileSystems."/tmp" =
  #  { device = "/dev/disk/by-uuid/b88c4b4d-16c2-4ede-8927-66cd954d0799";
  #    fsType = "btrfs";
  #    options = [ "subvol=tmp" ];
  #  };

  #fileSystems."/tmp" = {
  #  fsType = "tmpfs";
  #  device = "tmpfs";
  #  options = [ "nosuid" "nodev" "relatime" "size=14G" ];
  #};

  networking.useDHCP = lib.mkDefault true;

  powerManagement.cpuFreqGovernor = lib.mkDefault "powersave";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
