#!/usr/bin/env sh


# Shell options

export HISTSIZE=1000000000
export HISTFILE="$XDG_CACHE_HOME/terminal/history"

#
# Bash / ZSH common environment variables and functions
#

#export TIME_STYLE='+%Y-%m-%d %H:%M:%S'
#export LESS=-R
#export LESS_TERMCAP_mb=$'\E[1;31m'     # begin blink
#export LESS_TERMCAP_md=$'\E[1;36m'     # begin bold
#export LESS_TERMCAP_me=$'\E[0m'        # reset bold/blink
#export LESS_TERMCAP_so=$'\E[01;44;33m' # begin reverse video
#export LESS_TERMCAP_se=$'\E[0m'        # reset reverse video
#export LESS_TERMCAP_us=$'\E[1;32m'     # begin underline
#export LESS_TERMCAP_ue=$'\E[0m'        # reset underline
#eval $(dircolors --sh)
