#! /bin/sh

# importing colors
[ -f ~/.cache/wal/colors.sh ] && . ~/.cache/wal/colors.sh
[ -x ~/.local/bin/bspwm/bspwm_display_menu ] && ~/.local/bin/bspwm/bspwm_display_menu auto


# --- workflow --- #

bspc config split_ratio             0.6
bspc config borderless_monocle      true
bspc config single_monocle          false
bspc config gapless_monocle         true
bspc config ignore_ewmh_fullscreen  all
bspc config pointer_modifier        mod1  # mod3

# --- colors style --- #

bspc config window_gap    ${WINDOW_GAP:=22}
bspc config border_width  3
bspc config normal_border_color    $color8
bspc config focused_border_color   $color15
bspc config presel_feedback_color  $color15


# --- rules --- #

bspc config external_rules_command ~/.local/bin/bspwm/bspwm_external_rules


# --- dropdown terminals --- #

# starting terminals (programs are only run when you first unhidden the windows)
$TERMINAL -c dropdown_terminal     -e tmux new-session -t dropdown &
#$TERMINAL -c dropdown_calculator   -e $WORKON_HOME/m/bin/python -i -c 'import numpy as np; from numpy import *' &
$TERMINAL -c dropdown_calculator   -e julia --banner no &
$TERMINAL -c dropdown_mail         -e neomutt &
$TERMINAL -c dropdown_music_player -e ncmpcpp &


# running programs
picom --experimental-backends &
sxhkd &
# oppening sxhkd if it isn't running, else just reload it
##pgrep -x polybar || polybar my_bar &
##pgrep -x sxhkd && pkill -USR1 sxhkd || sxhkd &
