bar:
  height: 26
  location: top
  background: 000000ff

  right:
    - clock:
        time-format: "%H%M%S"
        date-format: "%Y%m%d"
        content:
          - string: {text: , font: "Font Awesome 5 Free:style=solid:size=12", right-margin: 3}
          - string: {text: "{date}", right-margin: 10}
          - string: {text: , font: "Font Awesome 5 Free:style=solid:size=12", right-margin: 3}
          - string: {text: "{time}", on-click: "$TERMINAL -e $EDITOR"}
