# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

let
  bootFat32Uuid = "A036-6953";
  swapUuid = "85e3a4a6-4258-4f7d-a48f-413210026a3d";
  nvmeBtrfsUuid = "185d4794-4a12-4ac5-87da-98e15851ded8";
  #hddBtrfsUuid = "30e4bc15-cf9d-4e23-8ef7-2db14db18bd1";
in {

  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = [ "nvme" "ahci" "thunderbolt" "xhci_pci" "usbhid" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  # space_cache (?)
  # https://wiki.tnonline.net/w/Btrfs/Space_Cache

  fileSystems = {

    "/boot" = {
      device = "/dev/disk/by-uuid/${bootFat32Uuid}";
      fsType = "vfat";
    };

    "/" = {
      device = "/dev/disk/by-uuid/${nvmeBtrfsUuid}";
      fsType = "btrfs";
      options = [ "subvol=@root" "compress=zstd" ];
    };

    "/nix" = {
      device = "/dev/disk/by-uuid/${nvmeBtrfsUuid}";
      fsType = "btrfs";
      options = [ "subvol=@nix" "compress=zstd" "noatime" ];
    };

    "/home" = {
      device = "/dev/disk/by-uuid/${nvmeBtrfsUuid}";
      fsType = "btrfs";
      options = [ "subvol=@home" "compress=zstd" ];
    };

    #"/home/marcosrdac/tmp" = {
    #  device = "/dev/disk/by-uuid/${hddBtrfsUuid}";
    #  fsType = "btrfs";
    #  options = [ "subvol=@marcosrdac/@tmp" "compress=zstd" ];
    #};

  };

  swapDevices = [
    { device = "/dev/disk/by-uuid/${swapUuid}"; }
  ];

  networking.useDHCP = lib.mkDefault true;

  #powerManagement.cpuFreqGovernor = lib.mkDefault "powersave";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
