# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

let
  bootFat32Uuid = "A036-6953";
  swapUuid = "85e3a4a6-4258-4f7d-a48f-413210026a3d";
  nvmeBtrfsUuid = "185d4794-4a12-4ac5-87da-98e15851ded8";
  hddNtfsUuid = "5FEF4B33100DFCB9";
in {

  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = [ "nvme" "ahci" "thunderbolt" "xhci_pci" "usbhid" "usb_storage" "sd_mod"
  ];
  boot.supportedFilesystems = [ "ntfs" ];


  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" "i2c_dev" "i2c-dev"
    "i2c-piix4"  # amd MOBO
    "i2c_piix4"  # amd MOBO
    "i2c-i801"  # intel MOBO
    "i2c_i801"  # intel MOBO
  ];
  boot.extraModulePackages = [ ];

  # space_cache (?)
  # https://wiki.tnonline.net/w/Btrfs/Space_Cache

  fileSystems = {

    "/boot" = {
      device = "/dev/disk/by-uuid/${bootFat32Uuid}";
      fsType = "vfat";
    };

    "/" = {
      device = "/dev/disk/by-uuid/${nvmeBtrfsUuid}";
      fsType = "btrfs";
      options = [ "subvol=@root" "compress=zstd" ];
    };

    "/nix" = {
      device = "/dev/disk/by-uuid/${nvmeBtrfsUuid}";
      fsType = "btrfs";
      options = [ "subvol=@nix" "compress=zstd" "noatime" ];
    };

    "/home" = {
      device = "/dev/disk/by-uuid/${nvmeBtrfsUuid}";
      fsType = "btrfs";
      options = [ "subvol=@home" "compress=zstd" ];
    };

    "/mnt/hdd" = {
      device = "/dev/disk/by-uuid/${hddNtfsUuid}";
      fsType = "ntfs3";
      options = [ "rw" "dmask=007" "fmask=117" "uid=${builtins.toString config.users.users.marcosrdac.uid}" "gid=${builtins.toString config.users.groups.hdd.gid}" ]
        ++ [ "auto" "nofail" ]  # do not mount at boot if any problems happen
      ;
    };

    #"/home/marcosrdac/tmp" = {
    #  device = "/dev/disk/by-uuid/${hddBtrfsUuid}";
    #  fsType = "btrfs";
    #  options = [ "subvol=@marcosrdac/@tmp" "compress=zstd" ];
    #};

  };

  swapDevices = [
    { device = "/dev/disk/by-uuid/${swapUuid}"; }
  ];

  networking.useDHCP = lib.mkDefault true;

  #powerManagement.cpuFreqGovernor = lib.mkDefault "powersave";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
