passwd:
    marcosrdac: ENC[AES256_GCM,data:jkuYghlu,iv:up/7FJ30jgkNY4jUd4b7YvTNjeRzSYA2knWxIR5vP7s=,tag:0bpSDyeFfUErTAxwO3DMfA==,type:str]
sops:
    age:
        - recipient: age1hjqdpuu3vpuhnjp9rt0fsk3hn5t7yjpjudcwq2u9tmnnaunh5psqgwacfa
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQOWJ2NzNkMFFrN3Q2eHB2
            Tjk5K29yQ1ZSWHFpa0lzT2RTa3VMRDIyaUVVCnh3ZFBrM0hXcHVsOElFaEt1dTFJ
            OWw2eEtIVkUrYkR4UStwQys5VTc3dWsKLS0tIEkraFVQaFIyb2hxY1RDV3k4bnJJ
            VDlpS0pmZjMyMnZsYVlRejkvRVVBcG8KdxCp2iUnkCZ7PNyU9uJ1a8PAtSaXk+Vn
            H5520Ht1L+wgmLHl18aGhAfUVcluumQCYeqkazlgXETCn1qsCvIb7g==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age15z4qkn0230tynxmx288j847rk8f7dt9uu4dj20raujrkj820350sngrgcs
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5Um1TUEo1ZU1qZlBrNVh4
            RVNwYjI2cGNURFhYVytmdzZvdFRBMDcvQmcwCklDREphc2gvcnZRWTlzYUNnY0ZI
            WlBzaHZQQnh0cEszSnlVN2txSkloZm8KLS0tIHIwWGtNNVhOVHZqajBMM2JzMzlO
            bnJmM1ovZGE2Tzl6dnpLVFh5VUtmNUkKcm9Kt6i/atacDaFjAa8mgv0PG/B8TasV
            TU2I0B93sE0hqifcmyZqMlJG9FUjp5Hh0TfdJ432cPSekHZZCbqGzQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1sm6kh3am3xquhtsyp0s602mhv3gtqzft95vgwhgpltuchwnwsqtqgln6ek
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1Vzk3MnUzbXhjQVFNR1Vt
            R1BVYmVrdkJpaFhpZUFkcGErSEZQU3ZVdEZVCnZRRGJHdUFDSmw2TC9adnpLZ0Vy
            R1hJOXpwekNGcVFkeWZZY3E1VFUyUGsKLS0tIHV3czU5WDVicTlZUDFKRllUbFpJ
            Wm1kWHRuNlB1eTBEMjVZYW1RU2tLZ00KhbJ63tdqJDVf2o38uy9pttUAoW3LTRoe
            midaPNHAgRPtA2h7AHQOVCTe0/X3ke8JmP5CcfzmcWNvspRIU/Mg2Q==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age12f3uju8radleeylaa88rz5x2n8rfvt3kyjyunf7u7m4ch5w2w99qe6398k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxZjFsdmtlTkw5ZG01ZFFO
            QlpLRkRHcFhjU3pkclVyRW5tK2tFL3dUS1FJCldLNTJQN3FjbjJ6M0JKaDhEL1Ez
            dnRoSXhRRUM5THdUVjBmQ3hMWmlyMWcKLS0tIHQ4UmlqMnRMYytVK2hEUlkxbmRT
            dncxVmc3NmZQdWoyWlZxTVR1cVZBSWMKGZaDp92bBbjPk3PLKcHoIskfq4iFFxe/
            Pv/70DoS4uXV0Raxae52cxoN+WTFw/Dw9WJ0aTxydGdEfNnroLfNnQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-06-11T01:25:21Z"
    mac: ENC[AES256_GCM,data:rLyJ2iYeR1XS/3XiMYVOh/o0m36FTbjIvGvQMCzbib5U4RelvL8XboRZpn3Cw9PgqGBXGm0mCOXHaVQj1K1CVECqzPVecehmnn0y3dfY4gAgd5FcnKEYFNTnNbvEJs9+Vv9r6sM1/KbjbL/RV0nJC7Pc20KYIXFJHwr02DIwiKo=,iv:9d/nAAW2gaIzOuS0wyIhsiOvYX6TjVydN1CS9iJ96Ck=,tag:NB46bnxLIrqCPY5AGcEh7g==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
