passwords:
    marcosrdac: ENC[AES256_GCM,data:4tylg2WzO85ebxKG4t1nhuHItEGpwD/tcTrUGCMHmBfC33yGQcz7oOfxQUpJh5IOdwrkpvkg+jQOm4e4CCCX5hhj9uDZfgCtz3aAVTycQHJ4gxN6sCz07g0jaR0Nc5yiQLeWWqBoaHq0vg==,iv:y1/p4s3ivYYTEYDNKjaKSSi0uJLPRVoR9icalb0Rg78=,tag:zyr9fAZkle2voCw0CZeN5A==,type:str]
    test: ENC[AES256_GCM,data:XiChXOhJHP9eQhjWb+f4bzHtW3sTaVxJwzAwHvLSInwzImsgPjMJE/OKOPofu1qzxW9qUwkIsSQzbKZJiQ1DhQ7Pe/o7PDouiaLWjrDTV6xuTZidu7nJpdLouzGMcBXqefnnHpciXJ8EuQ==,iv:+2d1a+8oAg+cZMDL3HN8STATifJ+ixRCUrEORvOtD3M=,tag:c2ksYASacBfraMkVSUOd8Q==,type:str]
#ENC[AES256_GCM,data:f0w1AjDTA9kwAWRmVKu4Smi1Hg==,iv:u2LJnd1p0pS1ZxvC2yxKe7zHEjuTPFdRY49e+F12wo4=,tag:e1uRmaCdWg7USCUINeN1TA==,type:comment]
#
#ENC[AES256_GCM,data:eHuawce/EdWxk+yYtyEUZqBFaMXT,iv:mqiW7wGP3OZcSFW/H5I3r9A40CJoPArneds+4vSXeJk=,tag:iHnQ9Roo+VB3gaKZW9ySfQ==,type:comment]
#ENC[AES256_GCM,data:C+CehR15XEVrA6ZH2nJwI0eGBa39,iv:ZDlZIwZVJKL+UidlQYfD/vewdFEOg9wFANZxjeMnL4I=,tag:a5D6vsaXMkIB93XOOLTSnQ==,type:comment]
#
#ENC[AES256_GCM,data:KXQfJPIsaYP38ZufthXgKn3Xv2vTuA==,iv:qpN3kDNrmR1PVSAXOcwTthPWvuUNIf80Nb2ss2/ZSJY=,tag:dJPiPI6fa0JNt2KwWRXDoA==,type:comment]
#ENC[AES256_GCM,data:6Iceb1twDgh3yTsiWDDKthZ+HbNstPpOu4Fwpdp8UAfqPy21GRKPCHoDOdCpAPKwaZC3B8M=,iv:zeCsUKhQCNgsukgzFGX/41xcXTzZP//+6N1go1peGTc=,tag:X5mt34DtR7Zl3aH0k845nQ==,type:comment]
#
#ENC[AES256_GCM,data:vAk92OSDPEU9BOKHCSDspWCZ7g==,iv:oXAyZ46gUo6wxSpGOHb88iDao00R2Ozsufc36avE+Q0=,tag:VTFc2RUAuVGz1QcfUA9FOQ==,type:comment]
#ENC[AES256_GCM,data:Tahy9t+Sd7An4naN,iv:+m9aF8Hg4m4P3TEujRr2zYpnDXdxpQKZgvKUWWudwbk=,tag:6RnGNbV7LIcSW7zX18HG0Q==,type:comment]
#
#ENC[AES256_GCM,data:ggewx/ma9nZcFWKEGMU=,iv:OJfP7uCrrGaespgrpgx7NjXadebWxGuvtn7eAo3v72Q=,tag:Jbzt0lcDrloqVCJEeQFNMQ==,type:comment]
#ENC[AES256_GCM,data:c+t3Is1yk+dQMcfA0NDvAtMlT8ci9EGeAHcuwkpaec2om/xw81vVWeSoRIfn,iv:77vNq1It5dn2viShI4O0+B1gO/+kfWvkUbuKDKqpoBI=,tag:F8NKzsXloSXt/m6448bqYA==,type:comment]
#ENC[AES256_GCM,data:C9jPnJF2SJzo/nf8/eCbc+rxDg==,iv:9CSY7MiDSWYzurHuPI80Uec8VUx7YlfQmEMcF4u/6/Q=,tag:LwDXwiNk4Opm3S4uxOHO0Q==,type:comment]
#ENC[AES256_GCM,data:FlvpJ41cjKKD4AbR+NMxjHY7L288zk2G9k3XS1KQqPDSIHjtv1+Y+4VPxAyTaY/kunLkR10OGUPZc1bxmGyn2GckTnpc2HnH5Dw=,iv:QFFNwfyuWf3oW6cK2BenBd9J85r1q91d9xgJ0j/jPCQ=,tag:N/PYWOoJtCOUhBkd/Xw31Q==,type:comment]
#
#ENC[AES256_GCM,data:lakOPyG7LelLLjtvOw==,iv:A6vYxs7y1HS4cYWMeXcJDj2lvNG0altahBURCkFz5Qs=,tag:tUgGHx71RySQKUVN9vWd+w==,type:comment]
#ENC[AES256_GCM,data:NlzgUK7YouoBUZcaVEZfRvIoT6QVoCG3Y1yYEpWYLYHnRzqp50FcjloXD4ezyTqUblzfV7++uS2E,iv:9DbUlPT/FLexwGLtRMfKuIbpnlTw5bzHnH21deNJw2A=,tag:ZN9jn57QQxz2Nx8XvC0nng==,type:comment]
sops:
    age:
        - recipient: age1hjqdpuu3vpuhnjp9rt0fsk3hn5t7yjpjudcwq2u9tmnnaunh5psqgwacfa
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQOWJ2NzNkMFFrN3Q2eHB2
            Tjk5K29yQ1ZSWHFpa0lzT2RTa3VMRDIyaUVVCnh3ZFBrM0hXcHVsOElFaEt1dTFJ
            OWw2eEtIVkUrYkR4UStwQys5VTc3dWsKLS0tIEkraFVQaFIyb2hxY1RDV3k4bnJJ
            VDlpS0pmZjMyMnZsYVlRejkvRVVBcG8KdxCp2iUnkCZ7PNyU9uJ1a8PAtSaXk+Vn
            H5520Ht1L+wgmLHl18aGhAfUVcluumQCYeqkazlgXETCn1qsCvIb7g==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age15z4qkn0230tynxmx288j847rk8f7dt9uu4dj20raujrkj820350sngrgcs
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5Um1TUEo1ZU1qZlBrNVh4
            RVNwYjI2cGNURFhYVytmdzZvdFRBMDcvQmcwCklDREphc2gvcnZRWTlzYUNnY0ZI
            WlBzaHZQQnh0cEszSnlVN2txSkloZm8KLS0tIHIwWGtNNVhOVHZqajBMM2JzMzlO
            bnJmM1ovZGE2Tzl6dnpLVFh5VUtmNUkKcm9Kt6i/atacDaFjAa8mgv0PG/B8TasV
            TU2I0B93sE0hqifcmyZqMlJG9FUjp5Hh0TfdJ432cPSekHZZCbqGzQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1sm6kh3am3xquhtsyp0s602mhv3gtqzft95vgwhgpltuchwnwsqtqgln6ek
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1Vzk3MnUzbXhjQVFNR1Vt
            R1BVYmVrdkJpaFhpZUFkcGErSEZQU3ZVdEZVCnZRRGJHdUFDSmw2TC9adnpLZ0Vy
            R1hJOXpwekNGcVFkeWZZY3E1VFUyUGsKLS0tIHV3czU5WDVicTlZUDFKRllUbFpJ
            Wm1kWHRuNlB1eTBEMjVZYW1RU2tLZ00KhbJ63tdqJDVf2o38uy9pttUAoW3LTRoe
            midaPNHAgRPtA2h7AHQOVCTe0/X3ke8JmP5CcfzmcWNvspRIU/Mg2Q==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age12f3uju8radleeylaa88rz5x2n8rfvt3kyjyunf7u7m4ch5w2w99qe6398k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxZjFsdmtlTkw5ZG01ZFFO
            QlpLRkRHcFhjU3pkclVyRW5tK2tFL3dUS1FJCldLNTJQN3FjbjJ6M0JKaDhEL1Ez
            dnRoSXhRRUM5THdUVjBmQ3hMWmlyMWcKLS0tIHQ4UmlqMnRMYytVK2hEUlkxbmRT
            dncxVmc3NmZQdWoyWlZxTVR1cVZBSWMKGZaDp92bBbjPk3PLKcHoIskfq4iFFxe/
            Pv/70DoS4uXV0Raxae52cxoN+WTFw/Dw9WJ0aTxydGdEfNnroLfNnQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-06-12T22:50:25Z"
    mac: ENC[AES256_GCM,data:PzWdu7xfzkN45vAH5AJepxBSEzc9SyV58erJAGnUw6niIS5BLSx+TqHdHcHihqe9xEQ8IA7CJHp3a9WZtkjsynWgANty0J4MnmKoMEzZ1AP4pJaDI7Y6oOcIrt3RgMHXDrxa0jskGQWLUNrsTJTleZmmR7aDq4EUDW/Zk8EZ0SY=,iv:oz6RK/ZM+ciZo5Lx24GfT//u35MkG8yZ8EwgW6VknB8=,tag:ndtJHzMZZMpqZJf4j9dk5A==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
